// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT senha_hash FROM usuarios WHERE email = $1
`

func (q *Queries) GetPasswordHash(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordHash, email)
	var senha_hash string
	err := row.Scan(&senha_hash)
	return senha_hash, err
}
